- name: Ruby provisioning
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  
  pre_tasks:
    - name: Ensure curl is installed
      package: name=curl state=present

  roles:
    - role: rvm_io.rvm1-ruby
      rvm1_rubies:
        - 'ruby-2.2.5'
        - 'ruby-2.3.1'

  tasks:
    - name: Install required system packages.
      apt: pkg={{ item }} state=installed update-cache=yes
      with_items: "{{ system_packages }}"
