- name: NodeJS provisioning
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install required system packages.
      apt: pkg={{ item }} state=installed update-cache=yes
      with_items: "{{ system_packages }}"
#    - name: install Git with default version
#      apt: name=git  state=present force=yes
